---

- name: Enable fuzzball-orchestrate subscription
  ansible.builtin.command: mtn dnf enable fuzzball-orchestrate

- name: Install rng-tools
  ansible.builtin.package:
    name: rng-tools
    state: present

- name: Start rngd
  ansible.builtin.service:
    name: rngd
    state: started
    enabled: yes

- name: Set default zone to 'trusted'
  ansible.builtin.command: firewall-cmd --set-default-zone=trusted
  register: default_zone_set
  changed_when:
  - '"ZONE_ALREADY_SET" not in default_zone_set.stderr'

- name: Add public interface to public zone
  ansible.builtin.firewalld:
    zone: public
    interface: "{{ public_interface }}"
    immediate: true
    permanent: false
    state: enabled

- name: Configure NetworkManager to ignore kubernetes-substrate interfaces
  ansible.builtin.copy:
    src: NetworkManager/conf.d/kubernetes-substrate.conf
    dest: /etc/NetworkManager/conf.d/kubernetes-substrate.conf
  notify: Reload NetworkManager

- name: Install fuzzball-substrate
  ansible.builtin.package:
    name: fuzzball-substrate
    state: present

- name: Configure fuzzball-substrate for standalone mode
  ansible.builtin.copy:
    src: fuzzball-substrate.env
    dest: /etc/default/fuzzball-substrate.env
  notify: Restart fuzzball-substrate

- name: Authorize admin host to ssh in
  ansible.posix.authorized_key:
    user: root
    key: "{{ hostvars[item]['iqube_ssh']['public_key'] }}"
  loop: "{{ groups['admin'] }}"
  ignore_errors: true
