---

- name: Install rng-tools
  ansible.builtin.package:
    name: rng-tools
    state: present

- name: Start rngd
  ansible.builtin.service:
    name: rngd
    state: started
    enabled: yes

- name: Disable firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no

- name: Configure NetworkManager to ignore fuzzball interfaces
  ansible.builtin.copy:
    src: NetworkManager/conf.d/iqube.conf
    dest: /etc/NetworkManager/conf.d/iqube.conf
  notify: Reload NetworkManager
