---

- name: Install rng-tools
  ansible.builtin.package:
    name: rng-tools
    state: present

- name: Start rngd
  ansible.builtin.service:
    name: rngd
    state: started
    enabled: yes

- name: Set default zone to 'trusted'
  ansible.builtin.command: firewall-cmd --set-default-zone=trusted
  register: default_zone_set
  changed_when:
    - '"ZONE_ALREADY_SET" not in default_zone_set.stderr'

- name: Configure NetworkManager to ignore fuzzball interfaces
  ansible.builtin.copy:
    src: NetworkManager/conf.d/iqube.conf
    dest: /etc/NetworkManager/conf.d/iqube.conf
  notify: Reload NetworkManager

- name: Create shared storage mountpoint
  ansible.builtin.file:
    path: "{{ fuzzball_sharedfs_directory }}"
    state: directory
    mode: 0755

- name: Install nfs-utils
  ansible.builtin.package:
    name: nfs-utils
    state: present
  when: fuzzball_sharedfs_nfs_source is defined

- name: Mount shared storage
  ansible.posix.mount:
    src: "{{ iqube_nfs_mount }}"
    path: /mnt/fuzzball/shared
    state: mounted
    fstype: nfs
  notify: Restart fuzzball-substrate
  when: fuzzball_sharedfs_nfs_source is defined

- name: Install fuzzball-substrate
  ansible.builtin.package:
    name: fuzzball-substrate
    state: present

- name: Configure fuzzball-substrate for standalone mode
  ansible.builtin.copy:
    src: fuzzball-substrate.env
    dest: /etc/default/fuzzball-substrate.env
  notify: Restart fuzzball-substrate

- name: Start fuzzball-substrate
  ansible.builtin.service:
    name: fuzzball-substrate
    state: started
    enabled: yes
