---

- name: Prepare shared storage NFS server
  hosts: iqube_nfs_server
  roles:
    - iqube_nfs_server
  tags:
    - nfs

- name: Install iqube
  hosts: iqube_admin
  roles:
    - iqube_admin
  tags:
    - iqube

- name: Prepare controller nodes for iqube
  hosts: iqube_controller
  roles:
    - iqube_controller
  tags:
    - controller

- name: Install fuzzball-cli
  hosts: iqube_admin
  roles:
    - fuzzball_cli
  tags:
    - fuzzball
