---

- name: Prepare shared storage NFS server
  hosts: iqube_nfs_server
  roles:
    - iqube_nfs_server
  tags:
    - iqube
    - nfs

- name: Deploy the iqube user
  hosts: iqube_controller,iqube_admin
  roles:
    - iqube_user
  tags:
    - iqube
    - user

- name: Configure iqube hosts entries
  hosts: iqube_controller,iqube_admin
  roles:
    - iqube_hosts
  tags:
    - iqube
    - hosts

- name: Prepare controller nodes for iqube
  hosts: iqube_controller
  roles:
    - iqube_controller
  tags:
    - iqube
    - controller

# - name: Attach compute node to fuzzball-orchestrate
#   hosts: iqube_compute
#   roles:
#     - squashfs-tools
#     - fuzzball-substrate
#     # - FB_POLL_CONFIG=/sharedStorage/substrate-config.yaml
#     # - nfs mount
#     - selinux # permissive

- name: Deploy fuzzball-orchestrate via iqube
  hosts: iqube_admin
  roles:
    - iqube_admin
  tags:
    - iqube
    - workstation
