---

- name: Install mountain
  hosts: all
  roles:
  - mountain

- name: NFS export /srv/fuzzball/shared from admin
  hosts: admin
  roles:
  - nfs_server

- name: Install IQube and fetch deployment artifacts
  hosts: admin
  roles:
  - iqube
  - iqube_kubernetes_substrate

- name: Prepare fuzzball-substrate standalone for kubernetes-substrate
  hosts: controller
  roles:
  - nfs_client
  - kubernetes_substrate_controller
