---

- name: Prepare rke2 cluster
  hosts: controller
  pre_tasks:
  - name: Install python3-kubernetes for Ansible to use
    ansible.builtin.package:
      name: python3-kubernetes
      state: present
  roles:
  - mountain
  - rke2
  - metallb
  - local_path_provisioner
  - helm
  - fuzzball_operator
  - fuzzball_orchestrate
