---

- name: NFS export from admin for Substrate configuration
  hosts: fuzzball_nfs_server
  roles:
  - nfs_server

- name: Deploy Fuzzball Orchestrate on a new RKE2 cluster
  hosts: fuzzball_controller
  pre_tasks:
  - name: Install python3-kubernetes for Ansible to use
    ansible.builtin.package:
      name: python3-kubernetes
      state: present
  roles:
  - mountain
  - rke2
  - metallb
  - local_path_provisioner
  - helm
  - fuzzball_operator
  - fuzzball_orchestrate

- name: Deploy the Fuzzball CLI on controllers
  hosts: fuzzball_controller
  roles:
  - fuzzball_cli

- name: Install Fuzzball Substrate on compute nodes
  hosts: fuzzball_compute
  roles:
  - mountain
  - nfs_client
  - fuzzball_substrate
