- name: Define fuzzball-substrate firewalld service
  ansible.builtin.copy:
    src: fuzzball-substrate.xml
    dest: /etc/firewalld/services/fuzzball-substrate.xml
    owner: root
    group: root
    mode: 0644
  notify: Restart firewalld
  tags:
    - firewalld

- name: permit traffic for fuzzball-substrate
  ansible.posix.firewalld:
    service: fuzzball-substrate
    permanent: yes
    immediate: yes
    state: enabled
  tags:
    - firewalld
