---

- name: Configure selinux to be permissive
  ansible.posix.selinux:
    state: permissive
    policy: targeted

- name: Install squashfs-tools
  ansible.builtin.package:
    name: squashfs-tools
    state: present

- name: Install nfs-utils
  ansible.builtin.package:
    name: nfs-utils
    state: present

- name: Create shared storage mountpoint
  ansible.builtin.file:
    path: /mnt/fuzzball/shared
    state: directory
    mode: 0755

- name: Mount shared storage
  ansible.posix.mount:
    src: "{{ iqube_nfs_server }}:/srv/fuzzball/shared"
    path: /mnt/fuzzball/shared
    state: mounted
    fstype: nfs
  notify: Restart fuzzball-substrate

- name: Distribute fuzzball-substrate package
  ansible.builtin.copy:
    src: "{{ fuzzball_substrate_rpm }}"
    dest: "/root/{{ fuzzball_substrate_rpm | basename }}"

- name: Install fuzzball-substrate
  ansible.builtin.package:
    name: "/root/{{ fuzzball_substrate_rpm | basename }}"
    disable_gpg_check: yes
    state: present

- name: Configure fuzzball-substrate
  ansible.builtin.template:
    src: fuzzball-substrate.env
    dest: /etc/default/fuzzball-substrate.env
  notify: Restart fuzzball-substrate

- name: Start fuzzball-substrate
  ansible.builtin.service:
    name: fuzzball-substrate
    state: started
    enabled: yes

- name: Populate service facts to check if firewalld is running
  ansible.builtin.service_facts:

- name: Configure firewalld if it is running
  include_tasks: firewalld.yaml
  when: "'firewalld' in ansible_facts.services and ansible_facts.services.firewalld.state == 'running'"
