---

- name: Enable fuzzball-orchestrate subscription
  ansible.builtin.command: mtn dnf enable fuzzball-orchestrate

- name: Install fuzzball-substrate-orchestrate
  ansible.builtin.package:
    name: fuzzball-substrate-orchestrate
    state: present

- name: Configure fuzzball-substrate
  ansible.builtin.template:
    src: fuzzball-substrate.env
    dest: /etc/default/fuzzball-substrate.env
  notify: Restart fuzzball-substrate

- name: Add cluster interface to trusted zone
  ansible.builtin.firewalld:
    zone: trusted
    interface: "{{ cluster_interface }}"
    immediate: true
    permanent: false
    state: enabled

- name: Start Fuzzball Substrate
  ansible.builtin.service:
    name: fuzzball-substrate
    state: started
