---

- name: Install apptainer
  ansible.builtin.package:
    name: https://github.com/apptainer/apptainer/releases/download/v1.0.3/apptainer-1.0.3-1.x86_64.rpm
    state: present
    disable_gpg_check: yes

- name: Distribute iqube package
  ansible.builtin.copy:
    src: "{{ iqube_rpm }}"
    dest: "/root/{{ iqube_rpm | basename }}"

- name: Install iqube
  ansible.builtin.package:
    name: "/root/{{ iqube_rpm | basename }}"
    disable_gpg_check: yes
    state: present

- name: Create directory for SIFs
  ansible.builtin.file:
    path: /var/lib/iqube
    state: directory
    mode: '0755'

- name: Log into container registry
  ansible.builtin.command:
    cmd: apptainer remote login --username=oauth2accesstoken --password-stdin oras://us-west1-docker.pkg.dev
    stdin: "{{ oauth2accesstoken }}"
  when: oauth2accesstoken is defined

- name: Pull fuzzball-stack.sif
  ansible.builtin.command:
    cmd: "apptainer pull /var/lib/iqube/fuzzball-stack.sif {{ iqube_fuzzball_stack }}"
    creates: /var/lib/iqube/fuzzball-stack.sif

- name: Pull kubernetes-substrate.sif
  ansible.builtin.command:
    cmd: "apptainer pull /var/lib/iqube/kubernetes-substrate.sif {{ iqube_kubernetes_substrate }}"
    creates: /var/lib/iqube/kubernetes-substrate.sif

- name: Place ssh private key
  ansible.builtin.copy:
    src: "{{ iqube_ssh_private_key }}"
    dest: ~iqube/.ssh/iqube
    owner: iqube
    group: iqube
    mode: 0600
  diff: no

- name: Configure iqube.yaml
  ansible.builtin.template:
    force: false
    src: iqube.yaml
    dest: ~iqube/iqube.yaml
    owner: iqube
    group: iqube
    mode: 0600

- name: Install fuzzball cli
  ansible.builtin.package:
    name: "{{ fuzzball_cli_rpm }}"
    state: present
    disable_gpg_check: yes

# - name: Initialize iqube
#   ansible.builtin.command:
#     cmd: iqube new /var/lib/iqube/kubernetes-substrate.sif
#     chdir: /home/iqube
#     creates: /home/iqube/config
#   become: yes
#   become_user: iqube

# - name: Bootstrap iqube
#   ansible.builtin.command:
#     cmd: /usr/local/bin/iqube bootstrap up
#     chdir: /home/iqube
#     creates: /home/iqube/config/.iqube/iqube.state
#   become: yes
#   become_user: iqube
#   run_once: yes

# - name: Provision fuzzball
#   ansible.builtin.command:
#     cmd: /usr/local/bin/iqube provision up
#     chdir: /home/iqube
#   become: yes
#   become_user: iqube
#   run_once: yes
