---

- name: Install iqube
  ansible.builtin.package:
    name: iqube
    state: present

- name: Log into container registry
  ansible.builtin.command:
    cmd: apptainer remote login --username=ciq --password-stdin {{ item }}
    stdin: "{{ ciq_mountain_access_key }}"
  loop:
    - "{{ iqube_fuzzball_stack }}"
    - "{{ iqube_kubernetes_substrate }}"
  when: ciq_mountain_access_key is defined

- name: Create directory for SIFs
  ansible.builtin.file:
    path: /usr/local/share/iqube
    state: directory
    mode: 0755

- name: Pull fuzzball-stack.sif
  ansible.builtin.command:
    cmd: "apptainer pull /usr/local/share/iqube/fuzzball-stack.sif {{ iqube_fuzzball_stack }}"
    creates: /usr/local/share/iqube/fuzzball-stack.sif

- name: Pull kubernetes-substrate.sif
  ansible.builtin.command:
    cmd: "apptainer pull /usr/local/share/iqube/kubernetes-substrate.sif {{ iqube_kubernetes_substrate }}"
    creates: /usr/local/share/iqube/kubernetes-substrate.sif

- name: Create directory for IQube context
  ansible.builtin.file:
    path: /root/iqube/
    state: directory
    mode: 0755

- name: Generate ssh key for IQube
  community.crypto.openssh_keypair:
    path: /root/iqube/id_ssh
  register:
    iqube_ssh

- name: Configure iqube.yaml
  ansible.builtin.template:
    src: iqube.yaml
    dest: /root/iqube/iqube.yaml
    mode: 0644
