- name: Restart fuzzball-substrate
  ansible.builtin.service:
    name: fuzzball-substrate
    state: restarted

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
