---

docker_registry_service_defaults:
  apiVersion: v1
  kind: Service
  metadata:
    name: registry-service
    namespace: docker-registry
  spec:
    type: LoadBalancer
    selector:
      run: registry
    ports:
    - name: registry-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000

docker_registry_service: {}
