---

- name: Install metallb
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  register: result
  retries: 5
  delay: 60
  until: result.failed is not defined or result.failed == false

- name: Configure metallb pool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default-pool
        namespace: metallb-system
      spec:
        addresses: "{{ rke2_metallb_pool_addresses }}"
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  register: result
  retries: 5
  delay: 60
  until: result.failed is not defined or result.failed == false

- name: Configure metallb advertisement
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: default-advertisement
        namespace: metallb-system
      spec:
        ipAddressPools:
        - default-pool
        interfaces:
        - "{{ cluster_interface }}"
    kubeconfig: /etc/rancher/rke2/rke2.yaml
