---

- name: Distribute IQube binary
  ansible.builtin.copy:
    src: "artifacts/{{ iqube['bin'] }}"
    dest: "/usr/local/bin/iqube"
    owner: root
    group: root
    mode: 0755

- name: Install apptainer
  ansible.builtin.package:
    name: https://github.com/apptainer/apptainer/releases/download/v1.0.2/apptainer-1.0.2-1.x86_64.rpm
    state: present
    disable_gpg_check: yes

- name: Log into container registry
  ansible.builtin.command:
    cmd: apptainer remote login --username=oauth2accesstoken --password-stdin oras://us-west1-docker.pkg.dev
    stdin: "{{ apptainer_oauth2accesstoken }}"
  become: yes
  become_user: iqube

- name: Pull fuzzball-stack.sif
  ansible.builtin.command:
    cmd: apptainer pull /home/iqube/fuzzball-stack.sif oras://us-west1-docker.pkg.dev/fuzzball-dev/iqube/fuzzball-stack:latest
    creates: /home/iqube/fuzzball-stack.sif
  become: yes
  become_user: iqube

- name: Pull kubernetes-substrate.sif
  ansible.builtin.command:
    cmd: apptainer pull /home/iqube/kubernetes-substrate.sif oras://us-west1-docker.pkg.dev/fuzzball-dev/iqube/kubernetes-substrate:latest
    creates: /home/iqube/kubernetes-substrate.sif
  become: yes
  become_user: iqube

- name: Place ssh private key
  ansible.builtin.copy:
    content: "{{ iqube['ssh_private_key'] }}"
    dest: ~iqube/.ssh/iqube
    owner: iqube
    group: iqube
    mode: 0600
  diff: no

- name: Configure iqube.yaml
  ansible.builtin.template:
    src: iqube.yaml
    dest: ~iqube/iqube.yaml
    owner: iqube
    group: iqube
    mode: 0600

# - name: Initialize iqube
#   ansible.builtin.command:
#     cmd: iqube new kubernetes-substrate.sif
#     chdir: /home/iqube
#     creates: /home/iqube/config
#   become: yes
#   become_user: iqube

# - name: Bootstrap iqube
#   ansible.builtin.command:
#     cmd: /usr/local/bin/iqube bootstrap up
#     chdir: /home/iqube
#     creates: /home/iqube/config/.iqube/iqube.state
#   become: yes
#   become_user: iqube
#   run_once: yes

# - name: Provision fuzzball
#   ansible.builtin.command:
#     cmd: /usr/local/bin/iqube provision up
#     chdir: /home/iqube
#   become: yes
#   become_user: iqube
#   run_once: yes

# - name: provision up
