---

# https://docs.rke2.io/known_issues
- name: Configure NetworkManager to ignore RKE2 interfaces
  ansible.builtin.copy:
    src: NetworkManager/conf.d/rke2-canal.conf
    dest: /etc/NetworkManager/conf.d/rke2-canal.conf
    mode: 0644
  notify: Reload NetworkManager

- name: Tune fs.inotify.max_user_instances
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: '8192'
    state: present

# https://docs.rke2.io/known_issues
- name: Disable firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: false
    state: stopped

- name: Install RKE2
  ansible.builtin.shell:
    cmd: "curl -sfL https://get.rke2.io | sh -"
    creates: /etc/rancher

- name: Configure RKE2 cluster IP
  ansible.builtin.template:
    src: rancher/rke2/config.yaml
    dest: /etc/rancher/rke2/config.yaml
    mode: 0644

- name: Start RKE2
  ansible.builtin.service:
    name: rke2-server
    state: started

- name: RKE2 shell profile
  ansible.builtin.copy:
    src: rke2.sh
    dest: /root/rke2.sh

# - name: Disable RKE2 ingress hostPorts
#   kubernetes.core.k8s:
#     state: present
#     apply: true
#     definition:
#       apiVersion: apps/v1
#       kind: DaemonSet
#       metadata:
#         name: rke2-ingress-nginx-controller
#         namespace: kube-system
#       spec:
#         template:
#           spec:
#             containers:
#             - name: rke2-ingress-nginx-controller
#               ports:
#               - containerPort: 80
#                 name: http
#                 hostPort: null
#               - containerPort: 443
#                 name: https
#                 hostPort: null
#     kubeconfig: /etc/rancher/rke2/rke2.yaml
