- name: Restart fuzzball-substrate
  ansible.builtin.service:
    name: fuzzball-substrate
    state: restarted

- name: Reload NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: reloaded
