---

- name: Install Local Path Provisioner
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.28/deploy/local-path-storage.yaml
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  register: result
  retries: 5
  delay: 10
  until: result.failed is not defined or result.failed == false

- name: Create /opt/local-path-provisioner
  ansible.builtin.file:
    path: /opt/local-path-provisioner
    state: directory

- name: restorecon /opt/local-path-provisioner
  ansible.builtin.command: restorecon -rv /opt/local-path-provisioner
