---

- name: Install CIQ public release repository
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  loop:
  - https://repository.ciq.com/ciq-public-release.rpm

- name: Install CIQ mountain
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - epel-release
  - mtn

- name: Enroll in CIQ Mountain
  ansible.builtin.command:
    cmd: "mtn enroll {{ mtn_access_key }}"
    creates: /etc/ciq/mountain/config.json
  when: mtn_access_key is defined and mtn_access_key != ""

- name: Enable fuzzball subscriptions
  ansible.builtin.command: "mtn dnf enable {{ item }}"
  loop: "{{ mtn_subscriptions }}"
