---

- name: Install nfs-utils
  ansible.builtin.package:
    name: nfs-utils
    state: present

- name: Deploy Fuzzball Orchestrate
  kubernetes.core.k8s:
    state: present
    apply: true
    namespace: fuzzball-system
    definition:
      apiVersion: deployment.ciq.com/v1alpha1
      kind: Fuzzball
      metadata:
        labels:
          app.kubernetes.io/name: fuzzball-orchestrate
          app.kubernetes.io/part-of: fuzzball
          app.kubernetes.io/managed-by: ansible
        name: fuzzball-orchestrate
      spec:
        image:
          repository: repository.ciq.com/fuzzball-testing/images
          username: ciq
          password: "{{ mtn_access_key }}"
          exclusive: false
        fuzzball:
          substrate:
            nfs:
              server: "{{ substrate_nfs_server }}"
              path: /srv/fuzzball/shared
              destination: /fuzzball/shared
          audit:
            storage:
              class: local-path
            localStorage: true
          log:
            storage:
              class: local-path
          schedule:
            storage:
              class: local-path
            gossipService:
              type: NodePort
          dns:
            externalService:
              type: NodePort
              kube:
                backendGatewayService:
                  type: LoadBalancer
                  annotations:
                    "metallb.universe.tf/allow-shared-ip": "ingress-and-fuzzball"
          storage:
            gossipService:
              type: NodePort
          workflow:
            callbackService:
              type: LoadBalancer
              annotations:
                "metallb.universe.tf/allow-shared-ip": "ingress-and-fuzzball"
        database:
          create:
            enableDebugPod: true
            persistence:
              class: local-path
            credentials:
              user: "{{ fuzzball_orchestrate_database_user }}"
              password: "{{ fuzzball_orchestrate_database_password }}"
        kyverno:
          create: {}
        tls:
          create: {}
        ingress:
          create:
            domain: "{{ fuzzball_orchestrate_domain }}"
            proxy:
              type: LoadBalancer
              annotations:
                "metallb.universe.tf/allow-shared-ip": "ingress-and-fuzzball"
        keycloak:
          create:
            createDatabase: true
            realmId: "{{ fuzzball_orchestrate_keycloak_realm }}"
            username: "{{ fuzzball_orchestrate_keycloak_admin_username }}"
            password: "{{ fuzzball_orchestrate_keycloak_admin_password }}"
            ingress:
              hostname: "{{ fuzzball_orchestrate_keycloak_hostname }}"
    kubeconfig: /etc/rancher/rke2/rke2.yaml
