---

- name: Deploy Fuzzball Orchestrate
  kubernetes.core.k8s:
    state: present
    apply: true
    namespace: fuzzball-system
    definition:
      apiVersion: deployment.ciq.com/v1alpha1
      kind: Fuzzball
      metadata:
        labels:
          app.kubernetes.io/name: fuzzball-orchestrate
          app.kubernetes.io/part-of: fuzzball
          app.kubernetes.io/managed-by: ansible
        name: fuzzball-orchestrate
      spec:
        image:
          repository: repository.ciq.com/fuzzball-testing/images
          username: ciq
          password: "{{ mtn_access_key }}"
          exclusive: false
        fuzzball:
          audit:
            localStorage: true
        database:
          create:
            enableDebugPod: true
            credentials:
              user: postgres
              password: postgres
        kyverno:
          create: {}
        tls:
          create: {}
        ingress:
          create:
            domain: ciq.local
        keycloak:
          create:
            createDatabase: true
            realmId: "{{ keycloak_realm }}"
            username: keycloak
            password: keycloak
    kubeconfig: /etc/rancher/rke2/rke2.yaml
