ssh:
  profiles:
    nodes:
      port: 22
      user: iqube
      key: /home/iqube/.ssh/iqube
cluster:
  nodes:
{% for node in groups['iqube_controller'] %}
    - name: {{ node }}
      roles:
        - controller
        - worker
      ssh:
        host: {{ hostvars[node]['iqube_ssh_host'] }}
        profile: nodes
      advertise-address: {{ hostvars[node]['iqube_advertise_address'] }}
{% endfor %}
  bootstrap:
    # control plane VIP needs to be on same network as the hosts above
    control-plane-vip: {{ iqube_control_plane_vip }}
    load-balancer:
      enabled: true
      ip-range:
        start: {{ iqube_ip_range_start }}
        end: {{ iqube_ip_range_end }}
  provisioners:
    - image: /home/iqube/fuzzball-stack.sif
      config:
        tls:
          self-signed: true
          lets-encrypt: null
        services:
          fuzzball:
            hostname: ""
            sharedfs-directory: /mnt/fuzzball/shared
          registry:
            hostname: ""
            enabled: true
          authentication:
            hostname: ""
            realm: ""
            admin-password: ""
