---

- name: Create a namespace for the docker registry
  kubernetes.core.k8s:
    name: docker-registry
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /etc/rancher/rke2/rke2.yaml

- name: Deploy a local docker registry
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          run: registry
        name: registry
        namespace: docker-registry
      spec:
        replicas: 1
        selector:
          matchLabels:
            run: registry
        template:
          metadata:
            labels:
              run: registry
          spec:
            containers:
            - name: registry
              image: registry:2
              ports:
              - containerPort: 5000
    kubeconfig: /etc/rancher/rke2/rke2.yaml

- name: Local docker registry service
  kubernetes.core.k8s:
    state: present
    definition: "{{ docker_registry_service_defaults | ansible.builtin.combine(docker_registry_service, recursive=true) }}"
    kubeconfig: /etc/rancher/rke2/rke2.yaml
